import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { type Sketch } from "@p5-wrapper/react";
import { NextReactP5Wrapper } from "@p5-wrapper/next";
import { Button } from "@/components/button";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const vals = new Array(8).fill(useRef<boolean>(false));

  const sketch: Sketch = (p5) => {
    p5.setup = () => p5.createCanvas(innerWidth, innerHeight);

    p5.draw = () => {
      p5.background(0);
      p5.fill(255);
      p5.push();
      for (const val of vals) {
        p5.text(val.current, 100, 100);
        p5.translate(100, 0);
      }
      p5.pop();

      // ビートサイクル内の現在時刻を計算
      let timeInBeat = p5.millis() % 500.0;

      // 円が見えるかどうかを決定
      let isVisible = timeInBeat < 500.0 / 2;

      if (isVisible) {
        p5.fill(255); // 円の色を赤に設定
        p5.ellipse(p5.width / 2, p5.height / 2, 200, 200); // 円を描画
      }
    };
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NextReactP5Wrapper sketch={sketch} />;
        <div className="interface">
          {(() => {
            const res = [];
            for (let i = 0; i < 8; i++) {
              res.push(<Button ref={vals[i]} />);
            }
            return res;
          })()}
        </div>
      </main>
    </>
  );
}
