import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { type Sketch } from "@p5-wrapper/react";
import { NextReactP5Wrapper } from "@p5-wrapper/next";
import { Button } from "@/components/button";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const val0 = useRef<boolean>(false);
  const val1 = useRef<boolean>(false);
  const val2 = useRef<boolean>(false);
  const val3 = useRef<boolean>(false);
  const val4 = useRef<boolean>(false);
  const val5 = useRef<boolean>(false);
  const val6 = useRef<boolean>(false);
  const val7 = useRef<boolean>(false);

  const vals = [val0, val1, val2, val3, val4, val5, val6, val7];
  let lastIsVisible = true;
  let head = 0;
  const bpm = 120;
  const beatDuration = 60000 / bpm; // 1分間に60,000ミリ秒

  const sketch: Sketch = (p5) => {
    p5.setup = () => p5.createCanvas(innerWidth, innerHeight);

    p5.draw = () => {
      p5.background(0);
      p5.fill(255);
      // ビートサイクル内の現在時刻を計算
      let timeInBeat = p5.millis() % beatDuration;

      // 円が見えるかどうかを決定
      let isVisible = timeInBeat < beatDuration / 2;

      const margin = (p5.width * 0.9 - 30) / 7;

      if (lastIsVisible !== isVisible && isVisible) {
        head = (head + 1) % 8;
      }

      if (isVisible) {
        if (vals[head].current) {
          p5.fill(255); // 円の色を赤に設定
        } else {
          p5.fill(100);
        }

        p5.push();
        p5.fill(255, 30, 30);
        p5.ellipse(
          p5.width * 0.05 + head * margin + 15,
          p5.height * 0.9 - 45,
          10
        );
        p5.pop();

        p5.ellipse(p5.width / 2, p5.height / 2, 200, 200); // 円を描画
      }

      lastIsVisible = isVisible;
    };
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NextReactP5Wrapper sketch={sketch} />;
        <p
          style={{
            position: "fixed",
            top: "50px",
            left: "50px",
            color: "white",
          }}
        >
          <span style={{ fontSize: "1.5rem" }}>{bpm}</span> bpm
        </p>
        <div className="interface">
          {(() => {
            const res = [];
            for (const val of vals) {
              res.push(<Button valueRef={val} />);
            }

            return res;
          })()}
        </div>
      </main>
    </>
  );
}
